version: "3.3"
services:

  # CB-Dragonfly
  cb-dragonfly:
    build:
      context: .
      dockerfile: Dockerfile
    image: cloudbaristaorg/cb-dragonfly:espresso-v0.1
    container_name: cb-dragonfly
    volumes:
      - ./conf:/go/src/github.com/cloud-barista/cb-dragonfly/conf
      - ./log:/go/src/github.com/cloud-barista/cb-dragonfly/log
    ports:
      - 8094:8094/udp
      - 9090:9090
    depends_on:
      - cb-dragonfly-etcd
      - cb-dragonfly-influxdb
    environment:
      - CBSTORE_ROOT=/go/src/github.com/cloud-barista/cb-dragonfly
      - CBLOG_ROOT=/go/src/github.com/cloud-barista/cb-dragonfly
      - CBMON_ROOT=/go/src/github.com/cloud-barista/cb-dragonfly
    restart: always
    security_opt:
      - no-new-privileges
#    network_mode: host

  # etcd for CB-Dragonfly
  cb-dragonfly-etcd:
    image: bitnami/etcd:3.3.11
    container_name: cb-dragonfly-etcd
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://cb-dragonfly-etcd:2379
    ports:
      - 2379:2379
      - 2380:2380
    restart: always
#    network_mode: host

  # InfluxDB for CB-Dragonfly
  cb-dragonfly-influxdb:
    image: influxdb:1.8-alpine
    container_name: cb-dragonfly-influxdb
    ports:
      - 8083:8083
      - 8086:8086
    environment:
      - PRE_CREATE_DB=cbmon
      - INFLUXDB_DB=cbmon
      - INFLUXDB_ADMIN_USER=cbmon
      - INFLUXDB_ADMIN_PASSWORD=password
      - INFLUXDB_HTTP_AUTH_ENABLED=true
    restart: always
#    network_mode: host

  # Chronograf for CB-Dragonfly
    cb-dragonfly-kapacitor:
      image: kapacitor:1.5
      container_name: cb-dragonfly-kapacitor
      ports:
        - 9092:9092
      environment:
        - KAPACITOR_HOSTNAME=kapacitor
        - KAPACITOR_INFLUXDB_0_URLS_0=http://cb-dragonfly-influxdb:8086
        - KAPACITOR_INFLUXDB_USERNAME=cbmon
        - KAPACITOR_INFLUXDB_PASSWORD=password
      volumes:
        - ./conf/kapacitor.conf:/etc/kapacitor/kapacitor.conf:ro
      depends_on:
        - cb-dragonfly-etcd
        - cb-dragonfly-influxdb
        - cb-dragonfly

  # Chronograf for CB-Dragonfly
  cb-dragonfly-chronograf:
    image: chronograf:1.8.4-alpine
    container_name: cb-dragonfly-chronograf
    ports:
      - 8888:8888
    command:
      - --influxdb-url=http://cb-dragonfly-influxdb:8086
      - --influxdb-username=cbmon
      - --influxdb-password=password
      - --kapacitor-url=http://cb-dragonfly-kapacitor:9092
      - --kapacitor-username=cbmon
      - --kapacitor-password=password
    depends_on:
      - cb-dragonfly-etcd
      - cb-dragonfly-influxdb
      - cb-dragonfly
#    network_mode: host
