#### Config for cb-dragonfly ####

# influxdb connection info
influxdb:
  endpointUrl: http://cb-dragonfly-influxdb:8086 # endpoint for influxDB
  database: cbmon
  userName: cbmon
  password: password

# etcd connection info
etcd:
  endpointUrl: http://cb-dragonfly-etcd:2379 # endpoint to etcd storage
  ttl: 60                 # time to live (s)

# collect manager configuration info
collectManager:
  collectorIp: 127.0.0.1 # local access endpoint to cb-dragonfly API server
  collectorPort: 8094    # udp port
  collectorCount: 1      # default collector count

# api server configuration info
apiServer:
  port: 9090

# monitoring interval configuration info
monitoring:
  agentInterval: 2        # agent interval (s)
  agentTTL : 5            # agent TTL (s)
  collectorInterval: 10   # aggregate interval (s)
  schedulingInterval: 10  # scale interval (s)
  maxHostCount:  10       # maximum host count per collector
